config/routes.rb
Rails.application.routes.draw do
  root "landing#main"
  get "/find_user_profile" => "landing#user_profile"
  get "/user/profile/:login" => "github_users#profile", as: "github_user_profile"

  get "/repositories/top/:count" => "github_repositories#top", as: "top_repositories"
  get "/repository/:repository" => "github_repositories#show", as: "github_repository"

  namespace "api" do
    get "/user/:handle" => "users#user"
    get "/user/:handle/similar" => "users#similar_users"
  end
end

app/models/github_pull_request.rb
class GithubPullRequest < ActiveRecord::Base
  belongs_to :github_user
  belongs_to :github_repository
end

app/models/github_push.rb
class GithubPush < ActiveRecord::Base
  belongs_to :github_repository
  belongs_to :github_user
end

app/models/github_repository.rb
class GithubRepository < ActiveRecord::Base
  has_many :github_pull_requests
  belongs_to :language

  def partial_name
    full_name.split('/').last
  end

  def contributors
    GithubUser.joins(pull_requests: :github_repository).
      select("github_users.login, count(github_pull_requests.id) as prs, github_repositories.id").
      where("github_repositories.id = :repo_id", repo_id: self.id).
      group("github_users.login, github_repositories.id").
      order("prs desc").
      distinct
  end

  def all_contributors
    GithubUser.joins(pull_requests: :github_repository).
      select("github_users.login, count(github_pull_requests.id) as prs, github_repositories.id").
      where("github_repositories.full_name LIKE '%/#{self.partial_name}'").
      group("github_users.login, github_repositories.id").
      order("prs desc").
      distinct
  end
end

app/models/github_user.rb
class GithubUser < ActiveRecord::Base
  has_many :pull_requests, class_name: "GithubPullRequest"
end

app/models/language.rb
class Language < ActiveRecord::Base
end

app/models/repository_ranking.rb
class RepositoryRanking < ActiveRecord::Base
  belongs_to :github_repository

  def ==(another_object)
    github_repository == another_object.github_repository &&
      pull_request_count == another_object.pull_request_count
  end
end

app/models/user_ranking.rb
class UserRanking < ActiveRecord::Base
  belongs_to :github_user
  def ==(another_object)
    github_user == another_object.github_user &&
      pull_request_count == another_object.pull_request_count
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
  respond_to :json

  def user
    @user = find_user
    @chart_data = Chart::GithubUserActivity.new(params[:handle], year_to_display)

    render :missing, :status => 422 unless @user
  end

  def similar_users
    @user = find_user
    @year = year_to_display
    @language_threshold = params[:language_threshold].present? ? params[:language_threshold].to_f : 60.0
    @activity_threshold = params[:activity_threshold].present? ? params[:activity_threshold].to_f : 20.0
    @similar_users = ArchiveExtensions::SimilarUsers.calculate(
      login: @user.login,
      year: @year,
      language_threshold: @language_threshold,
      activity_threshold: @activity_threshold).map { |user| user.login }

    render :missing, :status => 422 unless @user
  end

  private

  def find_user
    GithubUser.find_by_login(params[:handle])
  end

  def year_to_display
    params[:year].present? ? params[:year].to_i : Time.now.year
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/github_repositories_controller.rb
class GithubRepositoriesController < ApplicationController
  def top
    @language = Language.where("name ILIKE ?", params[:language]).first
    @top_repositories = ArchiveExtensions::TopActiveRepositories.
      for(count: params[:count].to_i, language: @language).page params[:page]
  end

  def show
    @repository = GithubRepository.find(params[:repository])
  end
end

app/controllers/github_users_controller.rb
class GithubUsersController < ApplicationController
  def profile
    @user = GithubUser.find_by_login(params[:login])
    @year = (params[:year] || Time.now.year).to_i
    @alternative_year = ([Time.now.year - 1, Time.now.year] - [@year]).first

    if @user
      render "profile"
    else
      render "missing_profile"
    end
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def main
  end

  def user_profile
    redirect_to github_user_profile_path(params[:github_user][:login])
  end
end

app/helpers/activity_helper.rb
module ActivityHelper
  def languages_for(github_login)
    ArchiveExtensions::Languages.for(github_login)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def paginate objects, options = {}
    options.reverse_merge!( theme: 'twitter-bootstrap-3' )

    super( objects, options )
  end
end

app/views/github_repositories/show.html.erb
<h1><%= link_to @repository.full_name, "https://github.com/#{@repository.full_name}" %></h1>

<h3>Top contributors (sorted by contributions)</h3>
<div id="contributor">
  <% @repository.contributors.each do |github_user| %>
    <div class="contributor">
      <span><%= link_to github_user.login, github_user_profile_path(github_user.login)  %></span>
    </div>
  <% end %>
</div>

app/views/github_repositories/top.html.erb
<h1>Top <%= params[:count] %> repositories <%= @language ? "in #{@language.name}" : '' %></h1>
<% @top_repositories.each do |top_item| %>
  <% repository = top_item.github_repository %>
  <% pr_count = top_item.pull_request_count %>
  <ul>
    <li>Name: <%= link_to repository.full_name, github_repository_path(repository.id) %></li>
    <li>Language: <%= repository.language.name %></li>
    <li>PR count: <%= pr_count %></li>
  </ul>
  <hr>
<% end %>

<%= paginate @top_repositories %>

app/views/github_users/_activity.html.erb
<h3>PR Activity Breakdown</h3>
<div id="chart"></div>
<%= render_chart(user_activity.chart, 'chart') %>

<!-- <h3>Commit Activity Breakdown</h3> -->
<!-- <div id="commit_chart"></div> -->
<%# render_chart(user_commit_activity.chart, 'commit_chart') %>

app/views/github_users/_languages.html.erb
<h3>Languages</h3>

<div id="bar_chart"></div>
<%= render_chart(chart, 'bar_chart') %>

app/views/github_users/missing_profile.html.erb
<h1>Missing profile</h1>
<p>
  Oops looks like we could not find your profile.<br>
  Most likely this means that we dont have enough data from the archives<br>
  to show your activity. But don't dispair, we will get there!<br>
  <br>
  Sorry for the inconvenience!
</p>

<%= link_to "Back to homepage", root_path %>
<br>
Or try finding the user again:
<%= form_for GithubUser.new, url: {action: "user_profile", controller: "landing"}, method: "get" do |form| %>
  <%= form.text_field :login, value: params[:login] %>
  <input name="commit" type="submit" value="Show Profile" />
<% end %>

app/views/github_users/profile.html.erb
<h1><%= link_to @user.login, "https://github.com/#{@user.login}" %></h1>

<%= render partial: "languages", locals: { chart: Chart::GithubUserTopLanguages.new(@user.login).chart } %>

<div class="page-header">
  <h2><%= @year %> specific data <small> Or switch to <%= link_to @alternative_year, github_user_profile_path(@user.login, year: @alternative_year)%></small></h2>
</div>

<%= render partial: "activity", locals: { user_activity: Chart::GithubUserActivity.new(@user.login, @year), user_commit_activity: Chart::GithubUserCommitActivity.new(@user.login, @year) } %>

<h3>Top 5 Repositories</h3>
<h4>Based on PRs</h4>
<ul>
  <% top_5_prs_repos = ArchiveExtensions::TopContributedRepositories.pr_for(login: @user.login, year: @year) %>
  <% if top_5_prs_repos.any? %>
    <% top_5_prs_repos.each do |repo| %>
      <li><%= link_to repo.fetch("repo").full_name, github_repository_path(repo.fetch("repo").id) %> - PR count: <%= repo.fetch("prs") %> </li>
    <% end %>
  <% else %>
    <li>Sorry we have no PR history</li>
  <% end %>
</ul>

<h4>Based on Commits</h4>
<ul>
  <% top_5_commit_repos = ArchiveExtensions::TopContributedRepositories.commit_for(login: @user.login, year: @year) %>
  <% if top_5_commit_repos.any? %>
    <% top_5_commit_repos.each do |repo| %>
      <li><%= link_to repo.fetch("repo").full_name, github_repository_path(repo.fetch("repo").id) %> - Commit count: <%= repo.fetch("commits") %> </li>
    <% end %>
  <% else %>
    <li>Sorry we have no commit history</li>
  <% end %>
</ul>

<h3>Similar Developers</h3>
<ul>
  <% similar_devs = ArchiveExtensions::SimilarUsers.calculate(login: @user.login, year: @year) %>
  <% if similar_devs.any? %>
    <% similar_devs.each do |user| %>
      <li><%= link_to user.login, github_user_profile_path(user.login, year: @year) %></li>
    <% end %>
  <% else %>
    <li>Could not find any similar devs.</li>
  <% end %>
</ul>

app/views/landing/main.html.erb
<p class="lead text-justify">
  This is Archive Observer, a weekend project that started to do some research on
  <a href="https://www.githubarchive.org/">Github Archive</a> data and how we can
  use it to build insight on development in general.<br><br>
  Each hour we parse the latest Github Archive and refresh our database. So you should
  expect new data every hour!<br><br>

  <strong>Note:</strong> contributions are calculated by identifying PRs being opened by users, and languages
  are identified by using the language determined as the main one for each repository.
</p>

<p class="text-center">
  <mark>I've started work on October 2015, so please bear with me until I can catchup with data</mark>
</p>
<ul class="list-group">
  <li class="list-group-item">
    <span class="badge"><%= number_with_delimiter(GithubPullRequest.count) %></span>
    Pull Requests
  </li>

  <li class="list-group-item">
    <span class="badge"><%= number_with_delimiter(GithubUser.count) %></span>
    Users
  </li>

  <li class="list-group-item">
    <span class="badge"><%= number_with_delimiter(GithubRepository.count) %></span>
    Repository
  </li>

  <li class="list-group-item">
    <span class="badge"><%= number_with_delimiter(GithubPush.count) %></span>
    Push data
  </li>
</ul>
<p class="text-center">
If you have any feedback, come find me at twitter <a href="https://twitter.com/guimansin" class="twitter-follow-button" data-show-count="false">@guimansin</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ArchiveObserver" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <script type="text/javascript" src="https://www.google.com/jsapi?autoload={
      'modules':[{
      'name':'visualization',
      'version':'1',
      'packages':['corechart']}]}"></script>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">ArchiveObserver</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Top 100 repositories", top_repositories_path(100) %></li>
          </ul>

          <%= form_for GithubUser.new, url: {action: "user_profile", controller: "landing"}, method: "get", html: { class: "navbar-form navbar-right" } do |form| %>
            <div class="form-group">
              <label for="login">Github Handle</label>
              <%= form.text_field :login, class: "form-control input-sm" %>
            </div>
            <button type="submit" class="btn btn-default">
              Find
            </button>
          <% end %>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->
    </div> <!-- /container -->

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-69353094-1', 'auto');
      ga('send', 'pageview');

    </script>
  </body>
</html>